### ISSUE TITLE
#US_01 : Ecran d'inscription

### ISSUE THREAD

**Issue by eddouiri** [Digitwan/Repository_Digitwan#1]
Nouvelle inscription fonctionnalité : minimisation de la form d'inscription et changement de la procédure de sauvegarde en back end pour accepter que les champs définis
Bug : Impossible de calculer ou de réserver si le mode de paiement n'est pas indiqué. Exemple pour le terrain "terrain FAR"

:+1: Correction validée

**Comment by Digitwan** [comment]
Bug : les boutons radio "Joueur/Partenaire" ne s'affichent pas.
![image](https://user-images.githubusercontent.com/38422954/38806224-766d50da-4170-11e8-9364-ac885ac1a64d.png)

:+1: Correction validée

**Comment by Digitwan** [comment]
Si un visiteur a déjà effectué une réservation avec son adresse email, le système ne lui permet pas de faire une nouvelle réservation avec le même email, le message suivant s'affiche : 
"Erreur! La valeur du champ adresse courriel est déjà utilisée."
