### ISSUE TITLE
#US_29 : Terrains en promo

### ISSUE THREAD

**Issue by Digitwan** [Digitwan/Repository_Digitwan#30]
dans la page d'accueil je vois 4 terrains qui sont en promo. Lorsque je filtre parmi les 3 villes disponibles dans la liste de recherche et je clique sur Trouver, je ne vois pas les terrains qui sont en promo

**Comment by eddouiri** [comment]
dans la page d'accueil tous les terrains affichés sont en promotion donc on affiche les valeurs des prix de promotion mais dans la partie de recherche des terrains on a dit qu'on va afficher les prix minimums pour chaque terrains c-a-d "terrain A pour la période matin : 10dh , l'AM : 20dh, le soir : 30dh" dans ce cas le prix qui sera affiché et le prix minimum de la période "matin" c'est pourquoi on affiche "à partir de".
En se basant sur la description dessus on peut constater que si le terrain A est en promotion pour la période "soir" il ne va pas être affiché en promotion mais son prix du la période matin qui sera affiché pour le joueur.
Pour le terrain que t'a vue en promotion parmi le résultat de recherche "terrain saada" c'est parce que sa période matin contient le prix minimum ainsi ce dernier contient une promotion dans la période matin c'est pourquoi le pourcentage de réduction est affiché
(Donc ce cas est a voir après...)
