### ISSUE TITLE
#US_35 : Modifier profil partenaire

### ISSUE THREAD

**Issue by eddouiri** [Digitwan/Repository_Digitwan#41]
La zone "Rue" de l'adresse bloque et attend avoir un numéro et non pas un texte.
Proposition : 
Zone 1 : N°
Zone 2 :  Rue/ Avenue
Zone 3 : Quartier
Et bloquer la mise à jour de l'email

**Comment by Digitwan** [comment]
Dans le détail du profil on retrouve les éléments suivants pour adresse : 
Rue Atlas N° 49 avenue Agdal Rabat Code Postale: 12000 
à remplacer par : 
N°49, Rue/Avenue Atlas Agdal 12000 Rabat
==> <N°>, Rue/Avenue <Nom de la rue> <quartier> <CP> <Ville>
