### ISSUE TITLE
#US_55 : Contenu des rubriques 2

### ISSUE THREAD

**Issue by Digitwan** [Digitwan/Repository_Digitwan#64]
-	Page conditions générales…
o	Laisser un seul titre entre les deux affichés « CONDITIONS … »
o	Article 1 :
	Enlever le texte : « En vertu de l'article 6 de la Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, »
	Commencer la phrase par une majuscule « Il est précisé… »
	Remonter le nom Digitwan dans la ligne après les deux points « édité par : »
	Enlever l’adresse postale de Digitwan
	Laisser son adresse email
	Enlever la ligne « le directeur de publication… »
o	Article 3, enlever la phrase « ou adresser un courrier… »
o	Article 6, enlever la phrase « ou avec les règles de la Nétiquette ; » et remonter la suite à ligne
o	7.2 Désinscription : Il faudra penser à ajouter un formulaire de désinscription du site
o	Supprimer l’article 10, et réorganiser les numéros des autres articles
o	Article 11 : enlever la phrase « lequel peut s’opposer… » et mettre un point à la fin de phrase
o	Article 12 : enlever la phrase « au sens des articles L. 335-2 et »

**Comment by eddouiri** [comment]
Remonter le nom Digitwan dans la ligne après les deux points « édité par : »
Enlever l’adresse postale de Digitwan
7.2 Désinscription : Il faudra penser à ajouter un formulaire de désinscription du site
